sudo: required
dist: trusty
language: node_js

node_js:
  - '4.4.2'

script:
  - 'npm install'
  - 'ls $TRAVIS_BUILD_DIR/*.js'

cache:
  directories:
    - node_modules

deploy:
  provider: releases
  api_key: "$GITHUB_API_TOKEN"
  file_glob: true
  file:
    - "$TRAVIS_BUILD_DIR/*.js"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
