sudo: required
dist: trusty
language: node_js

node_js:
  - '4.4.2'

script:
  - 'npm install'
  - 'ls $TRAVIS_BUILD_DIR/*.js'

cache:
  directories:
    - node_modules

before_deploy:
  - export RELEASE_FILE=$(ls $TRAVIS_BUILD_DIR/*.js)
  - echo "deploying $RELEASE_FILE to GitHub releases"

deploy:
  provider: releases
  api_key: "$GITHUB_API_TOKEN"
  file_glob: true
  file:
    - "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
